matrix:
  include:
    - language: java
      jdk:
        - openjdk8
      before_install:
        - gem install sass
      services:
        - redis-server
      script: mvn verify -pl access,access-common,admin,deposit,fcrepo-clients,metadata,persistence,security,services,services-camel,solr-ingest,solr-search,sword-server,migration-util
      sudo: false
      cache:
        directories:
        - "$HOME/.m2/repository"
      notifications:
        slack:
          secure: BXw3zt45l8M4Uu0rzyu4DhEza3PcXEw4eMrd+G9KLYFw039/XLPAhPOhcTrShRp8RR2e85NaTw5hJjl7chSpah+PvM9oLPV/yuwf6Wo9BZtSh1eFd+GWOWYyWlIALjUyDRQbqrrGM70aIky1gCGkb+93pJtJfyYWBW3TMWngYDQ=
    - language: node_js
      node_js:
        - 'lts/*'
      before_install:
        - npm i -g npm@6.9.0
        - npm install -g @vue/cli@3.7.0
        - npm --prefix static/js/vue-cdr-access install
        - npm --prefix static/js/admin/vue-permissions-editor install
      cache: npm
      script:
        - npm --prefix static/js/vue-cdr-access run test:unit
        - npm --prefix static/js/admin/vue-permissions-editor run test:unit