language: java
jdk:
  - oraclejdk8
services:
- redis-server
script: mvn test -pl access-common,access,admin,deposit,fcrepo-clients,metadata,persistence,security,solr-ingest,solr-search,sword-server,services-camel
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
notifications:
  slack:
    secure: BXw3zt45l8M4Uu0rzyu4DhEza3PcXEw4eMrd+G9KLYFw039/XLPAhPOhcTrShRp8RR2e85NaTw5hJjl7chSpah+PvM9oLPV/yuwf6Wo9BZtSh1eFd+GWOWYyWlIALjUyDRQbqrrGM70aIky1gCGkb+93pJtJfyYWBW3TMWngYDQ=
